version: 1
validation: sovereign
default_denom: skill
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000skill
- name: bob
  coins:
  - 10000token
  - 100000000skill
- name: charlie
  coins:
  - 5000token
  - 50000000skill
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000skill
- name: validator1
  bonded: 200000000skill
- name: validator2
  bonded: 100000000skill